export default function() {
  return {
    searchResults: [],
    jobList: [
      {
        version: "1.0",
        statusCode: 200,
        result: {
          items: [
            {
              jobId: "C71CD1954BA149BCAF42B25F775EA4FB1",
              positionName: "Position 1",
              companyName: "Company 1",
              durationDay: 0,
              durationDayText: "Fresh Ad",
              imageUrl:
                "http://localhost/bluecollar/Company/Job/000/000/000/avatar/13920170713010155805.jpg",
              distance: "8,53 km yakınında",
              latitude: 41.050968170166023,
              longitude: 29.062856674194339,
              cityName: "İstanbul",
              townName: "Çengelköy Mahallesi",
            },
            {
              jobId: "C71CD1954BA149BCAF42B25F775EA4FB2",
              positionName: "Position 2",
              companyName: "Company 2",
              durationDay: 0,
              durationDayText: "Fresh Ad",
              imageUrl:
                "http://localhost/bluecollar/Company/Job/000/000/000/avatar/13920170713010155805.jpg",
              distance: "8,53 km yakınında",
              latitude: 41.050968170166023,
              longitude: 29.062856674194339,
              cityName: "İstanbul",
              townName: "Ümraniye",
            },
            {
              jobId: "C71CD1954BA149BCAF42B25F775EA4FB3",
              positionName: "Position 3",
              companyName: "Company 3",
              durationDay: 0,
              durationDayText: "Fresh Ad",
              imageUrl:
                "http://localhost/bluecollar/Company/Job/000/000/000/avatar/13920170713010155805.jpg",
              distance: "8,53 km yakınında",
              latitude: 41.050968170166023,
              longitude: 29.062856674194339,
              cityName: "Adana",
              townName: "Çukurova",
            },
            {
              jobId: "C71CD1954BA149BCAF42B25F775EA4FB4",
              positionName: "Position 4",
              companyName: "Company 4",
              durationDay: 0,
              durationDayText: "Fresh Ad",
              imageUrl:
                "http://localhost/bluecollar/Company/Job/000/000/000/avatar/13920170713010155805.jpg",
              distance: "8,53 km yakınında",
              latitude: 41.050968170166023,
              longitude: 29.062856674194339,
              cityName: "İstanbul",
              townName: "Ümraniye",
            },
            {
              jobId: "C71CD1954BA149BCAF42B25F775EA4FB5",
              positionName: "Position 5",
              companyName: "Company 5",
              durationDay: 0,
              durationDayText: "Fresh Ad",
              imageUrl:
                "http://localhost/bluecollar/Company/Job/000/000/000/avatar/13920170713010155805.jpg",
              distance: "8,53 km yakınında",
              latitude: 41.050968170166023,
              longitude: 29.062856674194339,
              cityName: "Ankara",
              townName: "Çankaya",
            },
          ],
          total: 5,
        },
      },
    ],
    jobDetailsList: [
      {
        version: "1.0",
        statusCode: 200,
        result: {
          jobId: "C71CD1954BA149BCAF42B25F775EA4FB1",
          positionName: "Software Engineer",
          companyName: "Company 1",
          durationDay: 0,
          durationDayText: "Fresh Ad",
          imageUrl: "https://localhost/bluecollar/company/job/Default/6.jpg",
          countryCode: "TR",
          countryName: "Turkey",
          cityName: "İstanbul",
          townName: "Ümraniye",
          address:
            "Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey",
          postalCode: 34768,
          hasLatitude: true,
          hasLongitude: true,
          latitude: 41.0266502,
          longitude: 29.1157803,
          description:
            "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
          status: 1,
          contactPhone: {
            countryCallingCode: "+90",
            areaCode: "879",
            number: "9797979",
          },
        },
      },
      {
        version: "1.0",
        statusCode: 200,
        result: {
          jobId: "C71CD1954BA149BCAF42B25F775EA4FB2",
          positionName: "Software Engineer",
          companyName: "Company 2",
          durationDay: 0,
          durationDayText: "Fresh Ad",
          imageUrl: "https://localhost/bluecollar/company/job/Default/6.jpg",
          countryCode: "TR",
          countryName: "Turkey",
          cityName: "İstanbul",
          townName: "Ümraniye",
          address:
            "Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey",
          postalCode: 34768,
          hasLatitude: true,
          hasLongitude: true,
          latitude: 41.0266502,
          longitude: 29.1157803,
          description:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci[ng]velit, sed quia non numquam [do] eius modi tempora inci[di]dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum[d] exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? [33] At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat",
          status: 1,
          contactPhone: {
            countryCallingCode: "+90",
            areaCode: "879",
            number: "9797979",
          },
        },
      },
      {
        version: "1.0",
        statusCode: 200,
        result: {
          jobId: "C71CD1954BA149BCAF42B25F775EA4FB3",
          positionName: "Software Engineer",
          companyName: "Company 3",
          durationDay: 0,
          durationDayText: "Fresh Ad",
          imageUrl: "https://localhost/bluecollar/company/job/Default/6.jpg",
          countryCode: "TR",
          countryName: "Turkey",
          cityName: "Adana",
          townName: "Çukurova",
          address:
            "Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey",
          postalCode: 34768,
          hasLatitude: true,
          hasLongitude: true,
          latitude: 41.0266502,
          longitude: 29.1157803,
          description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          status: 1,
          contactPhone: {
            countryCallingCode: "+90",
            areaCode: "879",
            number: "9797979",
          },
        },
      },
      {
        version: "1.0",
        statusCode: 200,
        result: {
          jobId: "C71CD1954BA149BCAF42B25F775EA4FB4",
          positionName: "Food Engineer",
          companyName: "Company 4",
          durationDay: 0,
          durationDayText: "Fresh Ad",
          imageUrl: "https://localhost/bluecollar/company/job/Default/6.jpg",
          countryCode: "TR",
          countryName: "Turkey",
          cityName: "İstanbul",
          townName: "Ümraniye",
          address:
            "Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey",
          postalCode: 34768,
          hasLatitude: true,
          hasLongitude: true,
          latitude: 41.0266502,
          longitude: 29.1157803,
          description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          status: 1,
          contactPhone: {
            countryCallingCode: "+90",
            areaCode: "879",
            number: "9797979",
          },
        },
      },
      {
        version: "1.0",
        statusCode: 200,
        result: {
          jobId: "C71CD1954BA149BCAF42B25F775EA4FB5",
          positionName: "Food Engineer",
          companyName: "Company 5",
          durationDay: 0,
          durationDayText: "Fresh Ad",
          imageUrl: "https://localhost/bluecollar/company/job/Default/6.jpg",
          countryCode: "TR",
          countryName: "Turkey",
          cityName: "Ankara",
          townName: "Çankaya",
          address:
            "Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey",
          postalCode: 34768,
          hasLatitude: true,
          hasLongitude: true,
          latitude: 41.0266502,
          longitude: 29.1157803,
          description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          status: 1,
          contactPhone: {
            countryCallingCode: "+90",
            areaCode: "879",
            number: "9797979",
          },
        },
      },
    ],
    selectedJob: {},
    listResultError: {},
  };
}
